ACCOUNTS = ["cz_binance",
            "elonmusk",
            "nayibbukele",
            "VitalikButerin",
            "pmarca",
            "saylor",
            "100trillionUSD",
            "APompliano",
            "brian_armstrong",
            "TheCryptoLark",
            "SatoshiLite",
            "IvanOnTech",
            "woonomic",
            "RaoulGMI",
            "scottmelker",
            "aantonop",
            "elliotrades",
            "WClementeIII",
            "danheld",
            "maxkeiser",
            "PeterMcCormack",
            "novogratz",
            "CryptoHayes",
            "jackmallers",
            "DylanLeClair_",
            "Excellion",
            "waleswoosh",
            ]

CONVS =['1888377276385141071', '1887814602253086919', '1887920511050461618']